# Generated by Django 3.2 on 2023-07-13 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('counter_name', models.CharField(max_length=50)),
                ('counter_number', models.IntegerField()),
                ('counter_name2', models.CharField(max_length=50)),
                ('counter_number2', models.IntegerField()),
                ('counter_name3', models.CharField(max_length=50)),
                ('counter_number3', models.IntegerField()),
                ('counter_name4', models.CharField(max_length=50)),
                ('counter_number4', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_link', models.URLField(blank=True)),
                ('linkedin_link', models.URLField(blank=True)),
                ('youtube_link', models.URLField(blank=True)),
                ('instagram_link', models.URLField(blank=True)),
                ('about', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('number1', models.CharField(blank=True, max_length=20)),
                ('number2', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('open_and_closed_time', models.CharField(blank=True, max_length=50)),
                ('open_and_closed_day', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='directors/')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('facebook_link', models.URLField(blank=True)),
                ('linkedin_link', models.URLField(blank=True)),
                ('youtube_link', models.URLField(blank=True)),
                ('instagram_link', models.URLField(blank=True)),
                ('message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package_car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('caption', models.CharField(max_length=100)),
                ('car_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='car_images/')),
                ('price', models.IntegerField()),
                ('Car_Seats', models.CharField(max_length=100)),
                ('car_type', models.CharField(max_length=100)),
                ('menu', models.CharField(choices=[('airport_transfer', 'Airport Transfer'), ('inter_district_pick_drop', 'Inter District Pick&Drop'), ('rent_car_sylhet', 'Rent A Car in Sylhet'), ('rent_car_chittagong', 'Rent A Car in Chittagong'), ('rent_car_cox_bazar', "Rent A Car in Cox's Bazar"), ('day_tour_dhaka', 'Day Tour Nearby Dhaka'), ('rent_car_sajek_khagrachari', 'Rent A Car in Sajek Khagrachari'), ('tour_package', 'Tour Package'), ('hourly_packages', 'Flexible Hourly Packages')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Package_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sub_menu_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PickUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_name', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('location_from', models.CharField(max_length=550)),
                ('location_to', models.CharField(max_length=550)),
                ('load_capacity', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='pickup_images/')),
                ('description', models.TextField()),
                ('package_type', models.CharField(choices=[('Package 1 ton', 'Package 1 ton'), ('Package 2 ton', 'package 2 ton'), ('Package 3 ton', 'package 3 ton')], max_length=255)),
            ],
            options={
                'verbose_name': 'PickUp',
                'verbose_name_plural': 'PickUp',
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('caption', models.CharField(max_length=100)),
                ('car_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='car_images/')),
                ('price', models.IntegerField()),
                ('Car_Seats', models.CharField(max_length=100)),
                ('car_type', models.CharField(max_length=100)),
                ('menu', models.CharField(choices=[('hourly', 'Hourly Car Rental'), ('daily_dhaka', 'Daily Basis Rent A Car - Inside Dhaka'), ('daily_outside', 'Daily Basis Rent A Car - Outside Dhaka'), ('monthly', 'Monthly Car Rental'), ('pick_drop', 'Office Pick & Drop')], max_length=255)),
            ],
        ),
       
    ]
