# Generated by Django 3.2 on 2023-07-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('caption', models.CharField(max_length=100)),
                ('car_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='car_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('menu', models.CharField(choices=[('hourly', 'Hourly Car Rental'), ('daily_dhaka', 'Daily Basis Rent A Car - Inside Dhaka'), ('daily_outside', 'Daily Basis Rent A Car - Outside Dhaka'), ('monthly', 'Monthly Car Rental'), ('pick_drop', 'Office Pick & Drop')], max_length=255)),
            ],
        ),
    ]
