# Generated by Django 3.2 on 2023-07-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package_car',
            name='Car_Seats',
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='package_car',
            name='price',
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='Car_Seats',
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='price',
            field=models.IntegerField(max_length=15),
        ),
    ]
