# Generated by Django 3.2 on 2023-07-12 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
