# Generated by Django 3.2 on 2023-07-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='Car_Seats',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='pricing',
            name='car_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
