# Generated by Django 3.2 on 2023-07-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_name', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('location_from', models.CharField(max_length=550)),
                ('location_to', models.CharField(max_length=550)),
                ('load_capacity', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='pickup_images/')),
                ('description', models.TextField()),
                ('package_type', models.CharField(choices=[('package_one', 'Package One'), ('package_tow', 'Package Tow'), ('package_three', 'Package Three')], max_length=255)),
            ],
            options={
                'verbose_name': 'PickUp',
                'verbose_name_plural': 'PickUp',
            },
        ),
    ]
