# Generated by Django 3.2 on 2023-06-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('counter_name', models.CharField(max_length=50)),
                ('counter_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_link', models.URLField(blank=True)),
                ('linkedin_link', models.URLField(blank=True)),
                ('youtube_link', models.URLField(blank=True)),
                ('instagram_link', models.URLField(blank=True)),
                ('about', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('number1', models.CharField(blank=True, max_length=20)),
                ('number2', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('open_and_closed_time', models.CharField(blank=True, max_length=50)),
                ('open_and_closed_day', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='directors/')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('facebook_link', models.URLField(blank=True)),
                ('linkedin_link', models.URLField(blank=True)),
                ('youtube_link', models.URLField(blank=True)),
                ('instagram_link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package_car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='package_cars/')),
                ('car_name_or_model', models.CharField(max_length=100)),
                ('distance', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Package_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sub_menu_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services')),
                ('title', models.CharField(max_length=100)),
                ('car_type', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('time', models.CharField(max_length=100)),
                ('service_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
