# Generated by Django 3.2 on 2023-07-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='frontprofile',
            name='profile_image',
            field=models.ImageField(default='profile/no_profile.jpg', upload_to='profile_images/'),
        ),
    ]
