# Generated by Django 3.2 on 2023-07-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230709_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontprofile',
            name='profile_image',
            field=models.ImageField(default='no_profile.jpg', upload_to='profile_images/'),
        ),
    ]
